import FWCore.ParameterSet.Config as cms

hltAK4TrackJetsForJPT = cms.EDProducer("FastjetJetProducer",
    jetType = cms.string("TrackJet"),
    jetAlgorithm = cms.string("AntiKt"),
    rParam = cms.double(0.4),
    src = cms.InputTag("hltTrackRefsForJPT"),
    srcPVs = cms.InputTag("hltOfflinePrimaryVertices"),
    jetPtMin = cms.double(1.0),
    inputEtMin = cms.double(0.0),
    doPVCorrection = cms.bool(False),
    doAreaFastjet = cms.bool(False),
    doRhoFastjet = cms.bool(False),
    doPUOffsetCorr = cms.bool(False),
    Active_Area_Repeats = cms.int32(5),
    GhostArea = cms.double(0.01),
    Ghost_EtaMax = cms.double(6.0),
    MinVtxNdof = cms.int32(0),
    MaxVtxZ = cms.double(30.0),
    UseOnlyVertexTracks = cms.bool(False),
    UseOnlyOnePV = cms.bool(True),
    DzTrVtxMax = cms.double(0.5),
    DxyTrVtxMax = cms.double(0.2),
    nFilt = cms.int32(-1),
    useTrimming = cms.bool(False),
    useFiltering = cms.bool(False),
    usePruning = cms.bool(False),
    useMassDropTagger = cms.bool(False),
    useCMSBoostedTauSeedingAlgorithm = cms.bool(False),
)
