import FWCore.ParameterSet.Config as cms

hltJetPlusTrackZSPCorJetAntiKt4 = cms.EDProducer("JetPlusTrackProducer",
    UseInConeTracks = cms.bool(True),
    UseOutOfConeTracks = cms.bool(True),
    UseOutOfVertexTracks = cms.bool(True),
    JetSplitMerge = cms.int32(2),
    TrackQuality = cms.string("highPurity"),
    PtErrorQuality = cms.double(0.05),
    DeltaRCone = cms.double(0.4),
    MaxJetEnergy = cms.double(10000.0),
    UseMuons = cms.bool(False),
    UseElectrons = cms.bool(False),
    Muons = cms.InputTag("hltPhase2L3Muons"),
    Electrons = cms.InputTag("hltEgammaGsfElectrons"),
    ResponseMap = cms.string("CondFormats/JetMETObjects/data/CMSSW_538_response.txt"),
    EfficiencyMap = cms.string("CondFormats/JetMETObjects/data/CMSSW_538_TrackNonEff.txt"),
    LeakageMap = cms.string("CondFormats/JetMETObjects/data/CMSSW_538_TrackLeakage.txt"),
    nVtx = cms.int32(1),
    Verbose = cms.bool(False),
    src = cms.InputTag("hltAK4CaloJets"),
    srcTrackJets = cms.InputTag("hltAK4TrackJetsForJPT"),
    srcAddCaloJets = cms.InputTag("hltJetPlusTrackAddonSeedRecoForJPT"),
    extrapolations = cms.InputTag("hltTrackExtrapolatorForJPT"),
    srcPVs = cms.InputTag("hltPhase2PixelVertices"),
    tagName = cms.vstring("ZSP_CMSSW390_Akt_05_PU0"),
    tagNameOffset = cms.vstring(),
    PU = cms.int32(-1),
    FixedPU = cms.int32(0),
    UseZSP = cms.bool(False),
    alias = cms.untracked.string("hltJetPlusTrackZSPCorJetAntiKt4"),
    ptCUT = cms.double(15.0),
    dRcone = cms.double(0.4),
)
