import FWCore.ParameterSet.Config as cms

hltTrackWithVertexRefSelectorForJPT = cms.EDProducer("TrackWithVertexRefSelector",
    src = cms.InputTag("hltGeneralTracks"),
    vertexTag = cms.InputTag("hltOfflinePrimaryVertices"),
    quality = cms.string("highPurity"),
    d0Max = cms.double(999.0),
    dzMax = cms.double(999.0),
    normalizedChi2 = cms.double(999999.0),
    numberOfValidHits = cms.uint32(0),
    numberOfLostHits = cms.uint32(999),
    ptMin = cms.double(0.3),
    ptMax = cms.double(500.0),
    ptErrorCut = cms.double(5.0),
    etaMin = cms.double(0.0),
    etaMax = cms.double(5.0),
    nVertices = cms.uint32(2),
    vtxFallback = cms.bool(True),
    zetaVtx = cms.double(1.0),
    rhoVtx = cms.double(0.2),
)
